(* ::Package:: *)

(* ::Input:: *)
(*SetDirectory[NotebookDirectory[]];*)
(*<<MaTeX`;*)
(*fontSize=11; (* Beamer default font 11pt, 126 mm by 96 mm *)*)
(*SetOptions[MaTeX,FontSize->fontSize];*)
(*SetOptions[Plot,BaseStyle->{FontSize->fontSize,FontFamily->"Latin Modern Math"}];*)
(*SetOptions[$FrontEndSession,PrintingStyleEnvironment->"Working"];*)
(**)
